import sqlite3
import requests
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_summary(title, phase, sponsor, status, eligibility):
    print("AI writing summary... please wait...")
    prompt = f"""Write a professional 2-paragraph executive summary for this clinical trial.
Use formal clinical research language.

Trial Title: {title}
Phase: {phase}
Sponsor: {sponsor}
Status: {status}
Eligibility: {eligibility[:1000]}

Write only the 2 paragraphs. No headings. No extra text."""

    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": "llama3.2",
            "prompt": prompt,
            "stream": False
        }
    )
    return response.json()["response"]

def generate_report(nct_id):
    conn = sqlite3.connect("database/trials.db")
    cursor = conn.cursor()
    cursor.execute("""
        SELECT nct_id, title, status, phase, sponsor, 
               enrollment, start_date, eligibility 
        FROM trials WHERE nct_id=?
    """, (nct_id,))
    row = cursor.fetchone()
    conn.close()

    if not row:
        print("Trial not found")
        return

    nct_id, title, status, phase, sponsor, enrollment, start_date, eligibility = row

    summary = generate_summary(title, phase, sponsor, status, eligibility)

    os.makedirs("reports", exist_ok=True)
    filename = f"reports/{nct_id}_report.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4,
                            rightMargin=50, leftMargin=50,
                            topMargin=50, bottomMargin=50)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title',
        fontSize=18, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#1a3a5c'),
        spaceAfter=20)
    heading_style = ParagraphStyle('Heading',
        fontSize=13, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#1a3a5c'),
        spaceBefore=15, spaceAfter=8)
    body_style = ParagraphStyle('Body',
        fontSize=10, fontName='Helvetica',
        leading=16, spaceAfter=10)
    label_style = ParagraphStyle('Label',
        fontSize=9, fontName='Helvetica-Bold',
        textColor=colors.grey)

    content = []

    # Header
    content.append(Paragraph("ClinicalTrial OS", label_style))
    content.append(Paragraph(f"Trial Intelligence Report", title_style))
    content.append(Spacer(1, 10))

    # Trial details table
    data = [
        ["NCT ID", nct_id, "Status", status or "N/A"],
        ["Phase", phase or "N/A", "Sponsor", (sponsor or "N/A")[:30]],
        ["Enrollment", str(enrollment or "N/A"), "Start Date", start_date or "N/A"],
    ]
    table = Table(data, colWidths=[80, 150, 80, 150])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0f4f8')),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#1a3a5c')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#1a3a5c')),
        ('TEXTCOLOR', (0,0), (0,-1), colors.white),
        ('TEXTCOLOR', (2,0), (2,-1), colors.white),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.white),
    ]))
    content.append(table)
    content.append(Spacer(1, 15))

    # Title
    content.append(Paragraph("Trial Title", heading_style))
    content.append(Paragraph(title or "N/A", body_style))

    # Executive Summary
    content.append(Paragraph("Executive Summary", heading_style))
    content.append(Paragraph(summary, body_style))

    # Eligibility
    content.append(Paragraph("Eligibility Criteria", heading_style))
    eligibility_text = (eligibility or "Not available")[:800]
    content.append(Paragraph(eligibility_text, body_style))

    # Footer
    content.append(Spacer(1, 30))
    content.append(Paragraph(
        "Generated by ClinicalTrial OS — AI Platform for Clinical Research",
        label_style))

    doc.build(content)
    print(f"\nReport saved: {filename}")
    print("Open the reports/ folder to see your PDF")

if __name__ == "__main__":
    conn = sqlite3.connect("database/trials.db")
    cursor = conn.cursor()
    cursor.execute("SELECT nct_id FROM trials LIMIT 1")
    row = cursor.fetchone()
    conn.close()

    if row:
        print(f"Generating report for: {row[0]}")
        generate_report(row[0])